import canonicalLaneMathlib.AdmissibleClass
import chemicalEngineeringChemicalReactionEngineeringCanonicalLaneLean.ChemicalKinetics
import chemicalEngineeringChemicalReactionEngineeringCanonicalLaneLean.Thermodynamics
import chemicalEngineeringChemicalReactionEngineeringCanonicalLaneLean.ReactorDesign
import chemicalEngineeringChemicalReactionEngineeringCanonicalLaneLean.TransportPhenomena
import chemicalEngineeringChemicalReactionEngineeringCanonicalLaneLean.Catalysis

namespace HautevilleHouse
namespace ChemicalEngineeringChemicalReactionEngineeringCanonicalLaneLean

def ConstrainedChemicalReactionEngineeringClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_chemical_reaction_engineering_endgame (A : AdmissibleClass) :
    ConstrainedChemicalReactionEngineeringClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end ChemicalEngineeringChemicalReactionEngineeringCanonicalLaneLean
end HautevilleHouse